Fixed test.
borgius/qatest pull request #6
Opened 2017-08-14 09:30 UTC by ilya-luchnikov-qasunrise

This is my first test, I ask for recommendations.

2017-08-15 04:35 UTC, borgius requested changes

2017-08-15 04:35 UTC, borgius commented on testcases/demo_test.js
>  );
В данном тесте не нужно нажимать на каждом поле.
Лучше привязыватся к контексту.
Посмотри более правильный вариант, я тебе еще несколько примеров скину, оставшиеся попробуй сам переработать.
```JS
Scenario('User can create account @tests_group1', (I) => {
  I.amOnPage('/');
  I.waitForText('Create Account', c.timeout, '.build-a-garage');
  I.click('Create Account', '.build-a-garage');
  I.waitForElement('#account-create-form', c.timeout);
  within('#account-create-form', () => {
    I.fillField('FirstName', user.firstName);
    I.fillField('LastName', user.lastName);
    I.fillField('Email', user.email);
    I.fillField('Password', user.pwd);
    I.fillField('ConfirmPassword', user.pwd);
    I.click('Create My Account', '#createAccountSubmitButton');
  });
  I.waitForText(`${user.firstName}'s Account`, c.timeout, '#account-dropdown-wrapper');
});
```

2017-08-15 04:35 UTC, borgius commented on testcases/demo_test.js
> +);
```js
Scenario('User can login and logout @tests_group1', (I) => {
  I.amOnPage('/');
  I.waitForText('Sign In', c.timeout, '.my-account');
  I.click('Sign In', '.my-account');
  I.waitForElement('#account-login-form', c.timeout);
  within('#account-login-form', () => {
    I.fillField('Email', user.email);
    I.fillField('Password', user.pwd);
    I.click('Sign In', '.login-button-container');
  });
  I.waitForText(user.email, c.timeout, '.account-item');
  I.waitForText(`${user.firstName}'s Account`, c.timeout, '#account-dropdown-wrapper');
  I.click('#account-dropdown-wrapper');
  I.waitForText('Sign Out', c.timeout, '#account-dropdown');
  I.click('Sign Out', '#account-dropdown');
  I.waitForText('Sign In', c.timeout, '.my-account');
});
```

2017-08-15 04:35 UTC, borgius commented on testcases/demo_test.js
> +);
```js
Scenario('User can Find My Car for Volkswagen @tests_group1', (I) => {
  I.amOnPage('/');
  I.waitForElement('.text-search-input-buffer', c.timeout);
  within('.text-search-input-buffer', () => {
    I.fillField('.text-search-input', 'volkswagen');
    I.waitForText('Volkswagen', c.timeout, '.matching-results-container');
    I.click("//span[contains(text(), 'Volkswagen')]");
  });
  I.waitForText('VOLKSWAGEN', c.timeout, '.tag');
});
```

2017-08-15 04:35 UTC, borgius commented on testcases/demo_test.js
> +
Нам не нужно повторять то что мы уже делали

2017-08-15 14:56 UTC, Luchniko0ov commented
Я последовал вашим рекомендациям и исправил код.
Что то еще?

2017-08-17 12:52 UTC, alexandr-tsibukh-qasunrise commented on testcases/demo_test.js
> + 	I.click('.link-text');
Неужели на странице только один элемент с этим классом?

2017-08-17 12:52 UTC, alexandr-tsibukh-qasunrise commented on testcases/demo_test.js
> +	    I.fillField('#ConfirmPassword', data.pwd);
По-моему там всё хорошо находится по label-у, нет нужны использовать locator

2017-08-17 12:52 UTC, alexandr-tsibukh-qasunrise commented on testcases/demo_test.js
> +	    I.fillField('#ConfirmPassword', data.pwd);
Например в строке 52 ты уже заполняешь по label-у и всё окей

2017-08-17 12:52 UTC, alexandr-tsibukh-qasunrise commented
Хорошо что используешь фабрику, но нужно же её доставить в dependencies. Тогда тесты на travis пройдут.
Codeclimate жалуется на повторяющийся код. Либо вынеси в функцию, либо просто поменять как wontfix, потому что сейчас эти замечания не принципиальны, но зато check пройдёт.

2017-08-17 14:33 UTC, igor-pozhidaev-qasunrise commented on testcases/demo_test.js
> +	//User can select a vehicle from results
Сценарий Find Honda Civic < $15000, но после действий нет проверки последствий ни то что honda, ни то что меньше 15к.

2017-08-17 14:47 UTC, Luchniko0ov commented on testcases/demo_test.js
> + 	I.click('.link-text');
да.

2017-08-17 14:51 UTC, Luchniko0ov commented on testcases/demo_test.js
> +	    I.fillField('#ConfirmPassword', data.pwd);
Спасибо

2017-08-17 14:52 UTC, Luchniko0ov commented on testcases/demo_test.js
> +	//User can select a vehicle from results
Спасибо

2017-08-19 00:32 UTC, igor-pozhidaev-qasunrise commented on testcases/demo_test.js
> +	  	I.waitForElement('.filter-result:nth-child(2)', timeout);
В этом месте можно добавить ожидание конкретного текста в выпадающих предложениях.

2017-08-19 00:33 UTC, igor-pozhidaev-qasunrise commented on testcases/demo_test.js
> +	  	I.click('.filter-result:nth-child(2)');
После воздействия лучше сразу проверить эффект.

2017-08-19 00:37 UTC, igor-pozhidaev-qasunrise commented on testcases/demo_test.js
> + 	I.click('.link-text');
Но все равно там есть возможность добавить конкретики.

2017-08-19 00:39 UTC, igor-pozhidaev-qasunrise commented on testcases/demo_test.js
> +	//User can select a vehicle from results
Выше уже описал данный случай. Лучше сразу проверить результат. Потом в случае изменений можно будет быстрее найти проблему и исправить.

2017-09-25 03:19 UTC, closed without merging